version: "3.8"
services:
  app:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 0
    env_file:
      - .env
    volumes:
      - ./recordings:/app/recordings
#     environment:
#       POSTGRES_HOST: db
#       POSTGRES_PORT: "5432"
#       POSTGRES_USER: ${POSTGRES_USER:-postgres}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#       POSTGRES_DB: postgres
#     depends_on:
#       - db
#   db:
#     image: postgres:14-alpine
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER:-postgres}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#       POSTGRES_DB: postgres
#       PGDATA: /var/lib/postgresql/data/pgdata
#     ports:
#       - 5432:5432
#     restart: unless-stopped
#     volumes:
#       - db:/var/lib/postgresql/data/pgdata
#       - ./postgres-uuid-ossp.sh:/docker-entrypoint-initdb.d/postgres-uuid-ossp.sh
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
  
#   pgadmin:
#     image: dpage/pgadmin4:6.1
#     depends_on:
#       - db
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#     ports:
#       - 5433:80
#     restart: unless-stopped
#     volumes:
#       - pgadmin:/var/lib/pgadmin
# volumes:
#   db:
#   pgadmin:
