apiVersion: v1
kind: Pod
metadata:
  name: audio-meme-postgres
  labels:
    app: audio-meme
    component: db
spec:
  containers:
    - name: postgres
      image: postgres:14-alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: audio-meme-postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: audio-meme-postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: pgdata
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: audio-meme-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-meme-postgres
  labels:
    app: audio-meme
    component: db
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: audio-meme-postgres
spec:
  selector:
    app: audio-meme
    component: db
  ports:
    - port: 5432
      targetPort: 5432
