apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audio-meme
  name: audio-meme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-meme
  strategy: {}
  template:
    metadata:
      labels:
        app: audio-meme
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - image: registry.gitlab.com/cmongmang/audio-meme
          imagePullPolicy: IfNotPresent
          name: audio-meme
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          resources: {}
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  key: VERSION
                  name: audio-meme-version
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: audio-meme
                  key: CLIENT_ID
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: audio-meme
                  key: DISCORD_BOT_TOKEN
          volumeMounts:
            - mountPath: /app/recordings
              name: recordings
      volumes:
        - name: recordings
          persistentVolumeClaim:
            claimName: recordings
        - name: intros
          persistentVolumeClaim:
            claimName: intros
