apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  # TODO: Disable once https://github.com/kubernetes-sigs/kustomize/issues/1301 has viable solution
  disableNameSuffixHash: true

configMapGenerator:
  - name: audio-meme-version
    envs:
      - .env.version

secretGenerator:
  - name: audio-meme
    envs:
      - .env.app

images:
  - name: registry.gitlab.com/cmongmang/audio-meme

resources:
  - deployment.yaml
  - pvc.yaml
