apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-meme
  labels:
    app: audio-meme
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
